### ISSUE TITLE
Incomplete Tutorial "dynamic"

### ISSUE THREAD

**Issue by atremblay-seniorlink** [go-swagger/go-swagger.github.io#4]
The tutorial regarding Dynamic API Definitions stops mid sentence on the public site. 

https://goswagger.io/tutorial/dynamic/

**Comment by GlenDC** [comment]
This tutorial doesn't seem to exist any longer @casualjim, so I guess it could be closed?

**Comment by casualjim** [comment]
it's here: https://goswagger.io/tutorial/dynamic.html
